modLoader = "javafml"
loaderVersion = "[47]"
license = "All rights reserved"

[[mods]]
modId = "ok_zoomer"
version = "${version}"
displayName = "Ok Zoomer"
logoFile = "icon.png"
authors = "Ennui Langeweile and Up"
description = """
A zoom mod that is powerful, lean, and pretty customizable. The zoom is yours!
"""

[[dependencies.ok_zoomer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ok_zoomer]]
modId = "mixinextras"
mandatory = true
versionRange = "[0.4.1,)"
ordering = "NONE"
side = "CLIENT"

[mc-publish]
modrinth = "${modrinth_id}"
curseforge = "${curseforge_id}"
loaders = [ "forge", "neoforge" ]
