# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "1.20.4"
parchment = "2024.04.14"

quilt_loom = "1.6.7"
quilt_loader = "0.26.0-beta.1"

quilted_fabric_api = "9.0.0-alpha.8+0.97.0-1.20.4"
libzoomer = "0.8.1+1.20.1"
modmenu = "9.2.0-beta.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.20.4", version.ref = "parchment" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
libzoomer = { module = "maven.modrinth:libzoomer", version.ref = "libzoomer" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
