[versions]
minecraft = "1.20"
quilt_mappings = "1.20+build.1" # Latest version is available at https://lambdaurora.dev/tools/import_quilt.html
quilt_loader = "0.18.10" # Latest version is available at https://fabricmc.net/versions.html

quilted_fabric_api = "7.0.1+0.83.0-1.20"
libzoomer = "0.7.0+1.20"
mod_menu = "7.0.0"
spruceui = "5.0.0+1.20"
mixin_extras = "0.1.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
libzoomer = { module = "io.github.ennuil:LibZoomer", version.ref = "libzoomer" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
mixin_extras = { module = "com.github.LlamaLad7:MixinExtras", version.ref = "mixin_extras" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.2.+" }
machete = { id = "io.github.p03w.machete", version = "2.0.+" }
