modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"

[[mixins]]
config = "ok_zoomer.mixins.json"

[[mixins]]
config = "ok_zoomer_norge.mixins.json"

[[mods]]
modId = "ok_zoomer"
version = "${version}"
displayName = "Ok Zoomer"
logoFile = "icon.png"
authors = "Ennui Langeweile and Up"
description = """
Adds a highly configurable zoom key. By default, this mod provides its own take on zooming, however, through the config screen and its presets, you can drastically change the zoom with something more familiar, comfortable or useful. The zoom is yours!
"""

[[dependencies.ok_zoomer]]
modId = "neoforge"
type = "required"
versionRange = "[21.2.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ok_zoomer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.22)"
ordering = "NONE"
side = "CLIENT"

[mc-publish]
modrinth = "${modrinth_id}"
curseforge = "${curseforge_id}"
loaders = [ "neoforge" ]
