modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"

[[mixins]]
config = "ok_zoomer.mixins.json"

[[mixins]]
config = "ok_zoomer_norge.mixins.json"

[[mods]]
modId = "ok_zoomer"
version = "${version}"
displayName = "Ok Zoomer"
logoFile = "icon.png"
authors = "Ennui Langeweile and Up"
description = """
A zoom mod that is powerful, lean, and pretty customizable. The zoom is yours!
"""

[[dependencies.ok_zoomer]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0,21.2.0)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ok_zoomer]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ok_zoomer]]
modId = "okzoomer"
type = "incompatible"
reason = "The mod \"okzoomer-neoforge\", a now-redundant port of Ok Zoomer, causes interference with the official Ok Zoomer's zoom. This causes issues on the proper functioning of the zoom when both are used. Please remove one of the zoom mod JARs to proceed."
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[mc-publish]
modrinth = "${modrinth_id}"
curseforge = "${curseforge_id}"
loaders = [ "neoforge" ]
