name: Build Status
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew build --rerun-tasks
      - name: Detonate JARs (Fabric)
        run: python ./ci/hissboom.py "./fabric/build/libs/*.jar"
      - name: Detonate JARs (Neo)
        run: python ./ci/hissboom.py "./norge/build/libs/*.jar"
      - name: Upload build artifacts (Fabric)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Fabric-${{ github.sha }}
          path: |
            fabric/build/libs/*.jar
            !fabric/build/libs/*-dev.jar
      - name: Upload build artifacts (Neo)
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-Neo-${{ github.sha }}
          path: |
            norge/build/libs/*.jar
            !norge/build/libs/*-dev.jar
